### ISSUE TITLE
Some advice

### ISSUE THREAD

**Issue by justanotherbyte** [pikaninja/RoboDannyEnhcanced#25]
On request, I have reviewed this humble repo, created by the GitHub user, known as `pikaninja`, who is the creator of absolute mediocre discord bots such as Pokiland (something like that). Unfortunately, I have had to come to the conclusion, that this repo has reached the standards of `bad`. I, `justanotherbyte`, otherwise known as the poggest dev, have a few things to say about this repo, and I would like the owner `pikaninja` to take these words of gold dust seriously.

Please be a sane person and **don't** import everything from discord. Why did you have to touch the oh so innocent, yet infamous `requirements.txt` file. It was so innocent, so, simple. Please go back to pre-school and learn how to spell. It's `requirements.txt`. Also who uses bottom (apart from Daggy, who's just weird). There's much much more, which I would like to discuss, if you would like to discuss them, please DM me on discord at `moanie#9112`, however, I will probably just reply with "no". 

Thank you for your time.

**Comment by pikaninja** [comment]
no.

**Comment by justanotherbyte** [comment]
yes.
